export const filmActionTypes = Object.freeze({
	SET_ITEMS: 'SET_ITEMS',
	SET_PAGE: 'SET_PAGE',
	SET_TOTAL_RESULTS: 'SET_TOTAL_RESULTS',
	SET_PROPERTIES: 'SET_PROPERTIES',
	SET_HOVER: 'SET_HOVER',
	SET_FILM_ID: 'SET_FILM_ID',
	SET_GENRES_ID: 'SET_GENRES_ID'
})